Feature/mail template translation
emilschn/wdgwprestapi pull request #37
Opened 2020-12-21 14:42 UTC by emilschn

2020-12-21 16:58 UTC, hmeneuvrier requested changes

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +		//print_r( $translation_content );
@emilschn : commentaires à supprimer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +		if ( empty( $this->loaded_data->id_sib_en ) ) {
@emilschn : empty( $this->loaded_data->id_sib_en ) --> empty( $this->loaded_data['id_sib_"+$language_code] )

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +			//print_r( $template_fr_data );
@emilschn commentaires à supprimer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +			$result = $mailin->create_template( $data );
@emilschn commentaires à supprimer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +
@emilschn ça aussi, non ?

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +			$this->loaded_data->id_sib_en = $result[ 'data' ][ 'id' ];
$this->loaded_data->id_sib_en  --> $this->loaded_data['id_sib_"+$language_code]

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/sendinblue-template.php
> +				'id'			=> $this->loaded_data->id_sib_en,
$this->loaded_data->id_sib_en --> $this->loaded_data['id_sib_"+$language_code]

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/entities/email.php
> +					$template_id = $template_entity_data->id_sib_en;
@emilschn anticiper d'autres langues en faisant $template_id = $template_entity_data['id_sib_'+$user_recipient_language];

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +		curl_setopt( $curl_handle, CURLOPT_URL, $url );
@emilschn echo '<br><br>$url : <br>';
		print_r($url); 
		à suppriùmer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +				curl_setopt( $curl_handle, CURLOPT_CUSTOMREQUEST, 'PUT' );
@emilschn commentaire à supprimer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +			print_r( curl_error( $curl_handle ) );
@emilschn mettre ça dans des vrais logs

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +
@emilschn supprimer

2020-12-21 16:58 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +		$data[ 'categories' ] = '';
@emilschn à quoi pourrait correspondre cette catégorie ? si utile dans le futur, anticiper ?

2020-12-22 08:59 UTC, emilschn commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +	private static $transifex_project_slug = 'sendinblue-templates-mails';
prochainement, je ne vois pas ; on ne sait jamais, mais ça m'étonnerait...

2020-12-22 08:59 UTC, emilschn commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +		$data[ 'categories' ] = '';
aucune idée ! tu as une idée ? je ne vois pas du tout comment on pourrait catégoriser...

2020-12-22 10:38 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +	private static $transifex_project_slug = 'sendinblue-templates-mails';
ok

2020-12-22 10:38 UTC, hmeneuvrier commented on wp-content/plugins/wdgrestapi/libs/transifex.php
> +		$data[ 'categories' ] = '';
pas d'idée non plus

2020-12-22 10:46 UTC, merged